pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot pull requests
    conditions:
      - author=dependabot[bot]
      # condition
      # https://docs.mergify.com/conditions/#github-actions
      - and:
          - check-success~=^deploy-game
          - check-success~=^deploy-art
          - check-success~=^deploy-code
          - check-success~=^deploy-notes
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - and:
          - check-success~=^deploy-game
          - check-success~=^deploy-art
          - check-success~=^deploy-code
          - check-success~=^deploy-notes
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - and:
          - check-success~=^deploy-game
          - check-success~=^deploy-art
          - check-success~=^deploy-code
          - check-success~=^deploy-notes
    actions:
      merge:
        method: merge

  - name: automatic merge for test
    conditions:
      - author=DrAugus
      - or:
          - check-success=deploy-a
          - check-success=deploy-b
    actions:
      merge:
        method: merge
