pull_request_rules:
  - name: automatic merge for test
    conditions:
      - author=DrAugus
      - or:
          - check-success=deploy-a
          #- check-success=deploy-b
          - check-success=deploy-a(ubuntu-latest, 16, art/.output/public, augusmeow, art)
    actions:
      merge:
        method: merge
